server:
  port: 0

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.hibernate.format_sql: true

  datasource:
    username: "main"
    password: "main"
    url: jdbc:postgresql://localhost:9436/postgres
    driver-class-name: "org.postgresql.Driver"

    sql:
      init:
        mode: always

delivery:
  baseCost: 5
