spring:
  datasource:
    username: "main"
    password: "main"
    url: jdbc:postgresql://localhost:9436/postgres
    driver-class-name: "org.postgresql.Driver"

    sql:
      init:
        mode: always

server:
  port: 0