spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/