spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.hibernate.format_sql: true


  datasource:
    username: "main"
    password: "main"
    url: jdbc:postgresql://localhost:9433/postgres
    driver-class-name: "org.postgresql.Driver"

  sql:
    init:
      mode: always

server:
    port: 0